name: Build and Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build Docker images
      run: |
        gcloud auth configure-docker
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend-app:latest ./frontend
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend-app:latest ./backend

    - name: Push Docker images
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend-app:latest
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend-app:latest

    - name: Deploy Frontend to Cloud Run
      run: |
        gcloud run deploy frontend-app --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend-app:latest --region asia-south1 --platform managed --allow-unauthenticated

    - name: Deploy Backend to Cloud Run
      run: |
        gcloud run deploy backend-app --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend-app:latest --region asia-south1 --platform managed --allow-unauthenticated